---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by QIKU.
--- DateTime: 2022/12/28 18:24
---
local util=require("xLua/util")
local corMgr=CS.YooAsset.CoroutineManager.Instance
local WaitForSeconds=CS.UnityEngine.WaitForSeconds
local WaitForSecondsRealtime=CS.UnityEngine.WaitForSecondsRealtime
local WaitUntil=CS.UnityEngine.WaitUntil

function coroutine.start(func)
    return corMgr:StartCoroutine(util.cs_generator(func))
end
function coroutine.stop(cor)
    corMgr:StopCoroutine(cor)
end

function coroutine.wait(time,isUnScale)
    if isUnScale then
        coroutine.yield(WaitForSecondsRealtime(time))
    else
        coroutine.yield(WaitForSeconds(time))
    end
end
function coroutine.waitUntil(func)
    coroutine.yield(WaitUntil(func))
end

function coroutine.waitUntilWithArgs(func,...)
    coroutine.yield(WaitUntil(func))
    if func then
        func(...)
    end
end

function coroutine.stopAllCor()
    corMgr:StopAllCoroutines()
end

function coroutine.newStart(func,...)
    return corMgr:StartCoroutine(util.cs_generator(func,...))
end