ErrorCode=Class("ErrorCode")
---成功
ErrorCode.SUCCESS=200
---配置表异常
ErrorCode.SAMPLE_ERROR=201
---房间已销毁
ErrorCode.ROOM_DESTROYED=202
---失败
ErrorCode.FAIL=400
---错误的请求
ErrorCode.ERROR_REQ=401
---参数错误
ErrorCode.PARAM_ERROR=402
---已存在
ErrorCode.EXIST=403
---未找到
ErrorCode.NOT_FOUND=404
---禁止
ErrorCode.FORBID=405
---重复操作
ErrorCode.REPEAT_OP=406
---过期
ErrorCode.EXPIRE=407
---余额不足
ErrorCode.NOT_ENOUGHT=408
---Vip等级不足
ErrorCode.VIP_NOT_ENOUGHT=409
---未知错误
ErrorCode.UNKNOWN_ERROR=410
---服务器错误
ErrorCode.EXCEPTION=500