syntax = "proto3";//美元信息
message DollarsInfo {
  int32 coinIndexId = 1;  //美元符号图标坐标，如果有正确坐标，则说明触发了美元现金奖励
  repeated int32 dollarIndexIds = 2;  //钞票坐标
  repeated int64 dollarValueList = 3;  //钞票金额
  repeated int32 collectDollarIndexIds = 4;  //可收集的钞票坐标
}

//奖池信息
message PoolInfo {
  int32 id = 1;  //奖池id
  int32 initTimes = 2;  //初始倍数
  int32 maxTimes = 3;  //最大倍数
  int32 perSomeSec = 4;  //变化间隔时间
  int32 updateProp = 5;  //每过单位时间，奖池变化万分比
}

//每条中奖线信息
message ResultLineInfo {
  int32 id = 1;  //中奖线id
  repeated int32 iconIndexs = 2;  //这条线上中奖图标的坐标
  int32 times = 3;  //倍率
  int64 winGold = 4;  //中奖金币
}

//火车信息
message TrainInfo {
  int32 type = 1;  //火车类型(iconId)  15.金火车  19.绿火车 20.蓝火车  21.紫火车  22.红火车
  repeated int64 goldList = 2;  //中奖金额列表
  int32 poolId = 3;  //奖池ID
}

//请求,msgID=0x7001,desc=请求选择免费模式的游戏
message ReqChooseFreeModel {
  enum E_MsgID {def = 0; msgID = 28673;};
  int32 status = 1;  //选择类型  3.普通火车  4.黄金火车   5.免费游戏
}

//响应,msgID=0x7002,desc=返回选择免费模式的游戏
message ResChooseFreeModel {
  enum E_MsgID {def = 0; msgID = 28674;};
  int32 code = 1;  //状态码
}

//请求,msgID=0x7003,desc=选择投资地区
message ReqInvestArea {
  enum E_MsgID {def = 0; msgID = 28675;};
  int32 areaId = 1;  //地区id
}

//响应,msgID=0x7004,desc=选择投资地区返回
message ResInvestArea {
  enum E_MsgID {def = 0; msgID = 28676;};
  int32 code = 1;  //状态码
  repeated int64 goldList = 2;  //回报金额列表
  TrainInfo allWinTrainInfo = 3;  //3次都中奖，奖励的火车信息
  bool allAreaUnLock = 4;  //是否全地图解锁
}

//请求,msgID=0x7005,desc=请求开始游戏
message ReqStartGame {
  enum E_MsgID {def = 0; msgID = 28677;};
  int64 stakeVlue = 1;  //下注金额
}

//响应,msgID=0x7006,desc=开始游戏结果返回
message ResStartGame {
  enum E_MsgID {def = 0; msgID = 28678;};
  int32 code = 1;  //状态码
  repeated int32 iconList = 2;  //图标id列表
  repeated ResultLineInfo resultLineInfoList = 3;  //中奖信息
  int64 allWinGold = 4;  //累计中奖金币
  int32 status = 5;  //当前状态 0.正常  1.普通二选一  2.黄金列车二选一  3.二选一之拉普通火车  4.二选一之拉黄金火车  5.二选一之免费模式
  repeated TrainInfo trainInfoList = 6;  //火车信息
  DollarsInfo dollarsInfo = 7;  //美元信息
  int32 totalDollars = 8;  //累计的美元数量，进度条
  int32 remainFreeCount = 9;  //剩余免费次数
  repeated int32 choosableAreas = 10;  //投资可选区域，只有当触发投资游戏后才会有值
  int64 allGold = 11;  //玩家当前金币
  int64 bigWinShow = 12;  //大奖展示  1.sweet   2.big   3.mega  4.epic  5.legendary
}

//请求,msgID=0x7007,desc=请求配置信息
message ReqConfigInfo {
  enum E_MsgID {def = 0; msgID = 28679;};
}

//响应,msgID=0x7008,desc=请求配置信息
message ResConfigInfo {
  enum E_MsgID {def = 0; msgID = 28680;};
  int32 code = 1;  //状态码
  repeated int32 stakeList = 2;  //押注列表
  int32 defaultBet = 3;  //默认押注
  repeated PoolInfo poolList = 4;  //奖池信息
  int32 dollarTargetCount = 5;  //美元收集目标值
}

