--扑克牌配置

--牌的花色
POKER_CARDS_SUIT = 
{
	SPADE = 1,		--黑桃
	HEART = 2,		--红桃
	CLUB = 3,		--梅花
	DIAMOND = 4,	--方块
	JOKER = 5,		--王
}
--资源中间名
POKER_CARDS_SUIT_NAME =
{
	[1] = "spade",
	[2] = "heart",
	[3] = "club",
	[4] = "diamond",
	[5] = "joker",
}


--牌
POKER_CARDS = 
{
	[1] = {POKER_CARDS_SUIT.SPADE, 1},
	[2] = {POKER_CARDS_SUIT.SPADE, 2},
	[3] = {POKER_CARDS_SUIT.SPADE, 3},
	[4] = {POKER_CARDS_SUIT.SPADE, 4},
	[5] = {POKER_CARDS_SUIT.SPADE, 5},
	[6] = {POKER_CARDS_SUIT.SPADE, 6},
	[7] = {POKER_CARDS_SUIT.SPADE, 7},
	[8] = {POKER_CARDS_SUIT.SPADE, 8},
	[9] = {POKER_CARDS_SUIT.SPADE, 9},
	[10] = {POKER_CARDS_SUIT.SPADE, 10},
	[11] = {POKER_CARDS_SUIT.SPADE, 11},
	[12] = {POKER_CARDS_SUIT.SPADE, 12},
	[13] = {POKER_CARDS_SUIT.SPADE, 13},
	
	[14] = {POKER_CARDS_SUIT.HEART, 1},
	[15] = {POKER_CARDS_SUIT.HEART, 2},
	[16] = {POKER_CARDS_SUIT.HEART, 3},
	[17] = {POKER_CARDS_SUIT.HEART, 4},
	[18] = {POKER_CARDS_SUIT.HEART, 5},
	[19] = {POKER_CARDS_SUIT.HEART, 6},
	[20] = {POKER_CARDS_SUIT.HEART, 7},
	[21] = {POKER_CARDS_SUIT.HEART, 8},
	[22] = {POKER_CARDS_SUIT.HEART, 9},
	[23] = {POKER_CARDS_SUIT.HEART, 10},
	[24] = {POKER_CARDS_SUIT.HEART, 11},
	[25] = {POKER_CARDS_SUIT.HEART, 12},
	[26] = {POKER_CARDS_SUIT.HEART, 13},
	
	[27] = {POKER_CARDS_SUIT.CLUB, 1},
	[28] = {POKER_CARDS_SUIT.CLUB, 2},
	[29] = {POKER_CARDS_SUIT.CLUB, 3},
	[30] = {POKER_CARDS_SUIT.CLUB, 4},
	[31] = {POKER_CARDS_SUIT.CLUB, 5},
	[32] = {POKER_CARDS_SUIT.CLUB, 6},
	[33] = {POKER_CARDS_SUIT.CLUB, 7},
	[34] = {POKER_CARDS_SUIT.CLUB, 8},
	[35] = {POKER_CARDS_SUIT.CLUB, 9},
	[36] = {POKER_CARDS_SUIT.CLUB, 10},
	[37] = {POKER_CARDS_SUIT.CLUB, 11},
	[38] = {POKER_CARDS_SUIT.CLUB, 12},
	[39] = {POKER_CARDS_SUIT.CLUB, 13},
	
	[40] = {POKER_CARDS_SUIT.DIAMOND, 1},
	[41] = {POKER_CARDS_SUIT.DIAMOND, 2},
	[42] = {POKER_CARDS_SUIT.DIAMOND, 3},
	[43] = {POKER_CARDS_SUIT.DIAMOND, 4},
	[44] = {POKER_CARDS_SUIT.DIAMOND, 5},
	[45] = {POKER_CARDS_SUIT.DIAMOND, 6},
	[46] = {POKER_CARDS_SUIT.DIAMOND, 7},
	[47] = {POKER_CARDS_SUIT.DIAMOND, 8},
	[48] = {POKER_CARDS_SUIT.DIAMOND, 9},
	[49] = {POKER_CARDS_SUIT.DIAMOND, 10},
	[50] = {POKER_CARDS_SUIT.DIAMOND, 11},
	[51] = {POKER_CARDS_SUIT.DIAMOND, 12},
	[52] = {POKER_CARDS_SUIT.DIAMOND, 13},
	
	[53] = {POKER_CARDS_SUIT.JOKER, 1},
	[54] = {POKER_CARDS_SUIT.JOKER, 2},
}