---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/5/7 17:09
---

local class = Class("UIDeckGroundTile")

function class:ctor(go)
    --@type CS.UnityEngine.GameObject
    self.gameObject = go
    self.abName = "OutPut/UI/UIDeck/UITile"
    self.prefabName = "UITile"

    self.bgImage = self.gameObject:GetComponent("Image")
    self.eventTrigger = self.gameObject:GetComponent("EventTrigger")
    self.productIcon = ComponentUtilGet.Image(self.gameObject.transform, "img_product")

    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.PointerEnter, function(eventData)
        if self.onPointerEnter then
            self.onPointerEnter(self)
        end
    end)
    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.PointerExit, function(eventData)
        if self.onPointerExit then
            self.onPointerExit(self)
        end
    end)
    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.PointerDown, function(eventData)
        if self.onPointerDown then
            self.onPointerDown(self)
        end
    end)
    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.PointerUp, function(eventData)
        if self.onPointerUp then
            self.onPointerUp(self)
        end
    end)

    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.BeginDrag, function(eventData)
        if self.onBeginDrag then
            self.onBeginDrag(self)
        end
    end)

    self:AddEventTrigger(CS.UnityEngine.EventSystems.EventTriggerType.Drag, function(self,eventData)
        if self.onDrag then
            local pointerData = eventData:ConvertToPointerEventData(eventData)
            self.onDrag(Vector3(pointerData.position.x, pointerData.position.y, 0))
        end
    end)
    GlobalEvent.AddListener(EventID.OnTileDataChange, function(x,y)
        self:OnTileDataChange(x,y)
    end)
end

function class:SetData(tileData)
    self.x = tileData.x
    self.y = tileData.y
    self.tileSize = tileData.tileSize
    self.productData = GameDataManager.GetDeckTileData(self.x, self.y)
    self.startPosition = tileData.startPosition

    self.onDrag = tileData.onDrag
    self.onPointerEnter = tileData.onPointerEnter
    self.onPointerExit = tileData.onPointerExit
    self.onPointerDown = tileData.onPointerDown
    self.onPointerUp = tileData.onPointerUp
    self.onBeginDrag = tileData.onBeginDrag

    self:UpdateContent()
    
    print(self.gameObject.name, self.productData.productId, self.productData.productState)
end

function class:UpdateContent()
    self.gameObject.transform.localPosition = self.startPosition + Vector3(self.x * (self.tileSize + 3), self.y * (self.tileSize + 3), 0)
end

function class:AddEventTrigger(eventId, callback)
    local entry = CS.UnityEngine.EventSystems.EventTrigger.Entry()
    entry.eventID = eventId
    entry.callback = CS.UnityEngine.EventSystems.EventTrigger.TriggerEvent()
    entry.callback:AddListener(function(eventData)
        callback(self, eventData)
    end)
    self.eventTrigger.triggers:Add(entry)
end

function class:DisableProduct()
    self.productIcon.gameObject:SetActive(false)
end

function class:EnableProduct()
    self.productIcon.gameObject:SetActive(true)
end

function class:OnTileDataChange(x,y)
    if(self.x ~= x or self.y ~= y) then
        return
    end
    
end

return class